// This file is auto-generated by scripts/generate-icon-exports.js
// Do not edit manually

export { default as CopyDocument } from './CopyDocument.tsx'
export { default as Menu } from './Menu.tsx'
export { default as X } from './X.tsx'

type IconName =
  | 'CopyDocument'
  | 'Menu'
  | 'X'

export type { IconName }
